import { FOURSQUARE_CLIENT_ID, FOURSQUARE_CLIENT_SECRET, STREAM_API_KEY, STREAM_APP_ID, GOOGLE_GEO_API_KEY } from 'babel-dotenv';

export default {
    FOURSQUARE_CLIENT_ID,
    FOURSQUARE_CLIENT_SECRET,
    STREAM_API_KEY,
    STREAM_APP_ID,
    GOOGLE_GEO_API_KEY
};